lib/chromic_pdf/pdfa/ghostscript_impl.ex

Ghostscript 9.50 [enables `SAFER` mode](https://www.ghostscript.com/doc/current/History9.htm#Version9.50) by default and requires new `--permit-file-{read,write}` flags to allow it to access file.
9.27 (used in the CI image) can't deal with these flags unfortunately.

Enable ghostscript safer mode.

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/browser.ex
lib/chromic_pdf/pdf/protocol_macros.ex
lib/chromic_pdf/pdf/protocols/close_target.ex
lib/chromic_pdf/pdf/protocols/create_target.ex
lib/chromic_pdf/pdf/protocols/spawn_session.ex
lib/chromic_pdf/pdf/session.ex
test/integration/session_restart_test.exs

* This PR adds logic to `Session` that makes it automatically close and re-create its Target
* This in turn causes Chrome to create a new OS process (and kill the old one), keeping its overall memory footprint in check.

Restart session after a number of prints.

---

CHANGELOG.md
lib/chromic_pdf/template.ex

* Use `paperWidth` and `paperHeight` after all, as `@page` alone does
not seem to be effective.
* Add `zoom` rule to scale header & footer the same as the content.
* Print background colors by default.
|without zoom|with zoom|
|-|-|
|<img width="521" alt="Screenshot 2020-07-10 at 09 40 07" src="https://user-images.githubusercontent.com/96114/87129452-a30ff580-c291-11ea-895c-e76aded1ac20.png">|<img width="541" alt="Screenshot 2020-07-10 at 09 40 28" src="https://user-images.githubusercontent.com/96114/87129454-a4d9b900-c291-11ea-910a-bd0c3d956a61.png">|
<details>
<summary>Test code for above</summary>
```
defmodule ChromicPDF.Test do
def test do
styles = """
<style>
.test {
margin-top: 1mm;
height: 18mm;
width: 30mm;
background-color: green;
}
</style>
"""
html = [styles, ~s(<div …
```

Change Template options around.

---

mix.exs

When compiling with Elixir 1.11
```
warning: EEx.Engine.fetch_assign!/2 defined in application :eex is used by the current application but the current application does not directly depend on :eex. To fix this, you must do one of:
1. If :eex is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
2. If :eex is a dependency, make sure it is listed under "def deps" in your mix.exs
3. In case you don't want to add a requirement to :eex, you may optionally skip this warning by adding [xref: [exclude: EEx.Engine]] to your "def project" in mix.exs
Found at 28 locations:
lib/chromic_pdf/template.ex:233: ChromicPDF.Template.render_styles/1
lib/chromic_pdf/template.ex:237: ChromicPDF.Template.render_styles/1
lib/chromic_pdf/template.ex:238: …
```

Add :eex to extra_applications for Elixir 1.11.

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/browser.ex
lib/chromic_pdf/pdf/chrome.ex
lib/chromic_pdf/pdf/chrome_impl.ex
lib/chromic_pdf/pdf/connection.ex
test/unit/chromic_pdf/pdf/connection_test.exs

This changes our (not so-) "graceful" shutdown around to rely on Chrome
closing itself.
* Found out about the `nouse_stdio` port setting which is precisely what
we need in this case (using fd 3 & 4 of an external process for Erlang
communication!). This enables us to allow users to switch on Chrome
logging on demand, could be handy if Chrome crashes.
* Finally understood how `Process.flag(:trap_exit, true)` works in
combination with `c:GenServer.terminate/2`
* Hence got rid of the trap in `Connection` (it's only controlling the
port, no need to trap anything)
* Instead we forward the `:DOWN` message (from `Port.monitor`) in case
the Port is closed by Chrome itself up to the Browser.
* Extended the trap in `Browser` to send the `Browser.close` message and
then *wait* for a message …

Reorganize graceful shutdown.

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/api.ex
lib/chromic_pdf/supervisor.ex
mix.exs
test/integration/on_demand_test.exs
test/integration/session_restart_test.exs
test/integration/support/os_helper.ex

Adds an `on_demand` config option that prevents the supervisor from
starting up initially. Instead, it spawns an Agent process to store the
configuration for us, and dynamically launches the supervisor (unnamed)
as needed, and stops it after use.
This should help reducing the "zombie process" pain in development when
stopping a server / iex shell with Ctrl+C.
Addresses #56.

"On Demand" mode.

---

CHANGELOG.md
lib/chromic_pdf/pdf/protocol.ex
lib/chromic_pdf/pdf/protocol_macros.ex
lib/chromic_pdf/pdf/protocols/print_to_pdf.ex
lib/chromic_pdf/pdf/protocols/spawn_session.ex
lib/chromic_pdf/pdfa/ghostscript_worker.ex
lib/chromic_pdf/utils.ex
test/integration/fixtures/image_with_text.svg
test/integration/pdf_generation_test.exs

This patch changes the `PrintToPDF` protocol to wait for Chrome's
`Page.loadEventFired` notification after `setDocumentContent` instead of
only for the response of the call. This gives Chrome time to fetch external
resources (`<img>`, `<script>`, etc.) from URLs before printing the page.
* Change the handling of `:await`-type protocol steps to allow multiple
successive responses/notifications to arrive out-of-order and wait for
all of them before continuing with the next `:call` step. This makes
it possible to wait for both the response of the `setDocumentContent`
call and the `loadEventFired` notification.
* Change the "blanking" of the page after printing to navigate to a local
file (`priv/blank.html`) instead of `about:blank`, as otherwise Chrome
refuses to fetch any `file:///` URLs …

[#80] Wait for Page.loadEventFired after setDocumentContent.

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/browser/channel.ex
lib/chromic_pdf/pdf/browser/session_pool.ex
lib/chromic_pdf/supervisor.ex
test/integration/pdf_generation_test.exs

This patch adds a new global `timeout` option that can be passed via the
session pool configuration and which allows to configure the GenServer
timeout (essentially how long we wait for "protocols" to complete).
Fixes #83.

[83] Add global timeout option for browser interaction.

---

README.md
lib/chromic_pdf/api.ex
lib/chromic_pdf/supervisor.ex
test/integration/pdfa_generation_test.exs
test/integration/zugferd_test.exs

* Move ZUGFeRD test to its own file.
* Remove mention of ZUGFeRD from `convert_to_pdfa/2` doc.
* Typespec `:info` option with allowed keys.

Minor doc improvements to PDF/A generator.

---

CHANGELOG.md
lib/chromic_pdf/pdf/protocol_macros.ex
lib/chromic_pdf/pdf/protocols/capture_screenshot.ex
lib/chromic_pdf/pdf/protocols/navigate.ex
lib/chromic_pdf/pdf/protocols/print_to_pdf.ex
lib/chromic_pdf/pdf/protocols/reset_target.ex
lib/chromic_pdf/pdf/protocols/spawn_session.ex
lib/chromic_pdf/supervisor.ex

* Add new `include_protocol` macro to the `ProtocolMacros` which builds
a shared protocol and merges its steps into the current protocol.
* Extract `Navigate` and `Blank` protocols from `PrintToPDF` and use
them in `CaptureScreenshot` (gains all navigational options from
`print_to_pdf/2`!) and `SpawnSession`.

Shared protocol fragments.

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/connection.ex
lib/chromic_pdf/pdf/connection/connection_lost.ex
test/integration/connection_lost_test.exs
test/unit/chromic_pdf/pdf/connection_test.exs

* When Chrome dies at startup, display a helpful error message.
* Improve sandbox docs, mention Docker & seccomp.
Addresses #120.

[120] Explicit connection lost error and helpful sandbox docs.

---

README.md

As the README is part of the hexdocs documentation (see mix.exs), links
need to be absolute.
```
$ mix docs
Generating docs...
warning: documentation references file "examples/phoenix" but it does not exist
README.md
```

Fix broken link in docs.

---

lib/chromic_pdf/pdf/chrome_impl.ex

This adds the Chromium path for macOS users.
Edit: reference is https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/eloston-chromium.rb that does not add the binary to $PATH.

Add Chromium path on macOS

---

mix.exs

Be more flexible with telemetry version to avoid blocking deps.update
That has become a common pattern, see https://github.com/elixir-ecto/ecto_sql/commit/7209cce1bafb6769f7447b99353a52bfb0c158ae and https://github.com/beam-telemetry/telemetry_metrics/commit/ddc41e5c64d0ea416d810529f1a251c738e8d568
Ref https://github.com/beam-telemetry/telemetry/blob/main/CHANGELOG.md#100

Support latest telemetry

---

CHANGELOG.md
lib/chromic_pdf/pdf/protocol.ex
lib/chromic_pdf/supervisor.ex
test/integration/pdf_generation_test.exs

[[#134]](https://github.com/bitcrowd/chromic_pdf/issues/134)
This patch adds "can't use external URLs" to list of caveats of
header/footer templates, and adds an error log statement when we receive
the `Inspector.targetCrashed` message.
See https://elixirforum.com/t/chromicpdf-pdf-generator/29473/30 and above
Closes #134 
/cc @timkonieczny

[#134] External URLs in header/footer templates crash

---

lib/chromic_pdf/pdfa/ghostscript_impl.ex
test/integration/pdfa_generation_test.exs

https://hexdocs.pm/elixir/1.12/System.html#cmd/3
> arguments do not need to be escaped or quoted for shell safety
The arguments seem to confuse `ghostscript`

[#153] Possibly incompatible with Ghostscript 9.56.1

---

lib/chromic_pdf/pdf/protocol.ex

Hi there, recently I investigated an issue where, under stress, Chromium spawned by ChromicPDF would crash inside of the Docker container.
I eventually found that the `--disable-dev-shm-usage` flag fixes the issue. By default Docker containers have 64 MB of shared memory available in /dev/shm, so under stress, this shared memory is exhausted, and Chromium crashes: https://github.com/puppeteer/puppeteer/blob/v1.0.0/docs/troubleshooting.md#tips
`--disable-dev-shm-usage` fixes this by using /tmp instead, at the cost of potentially reduced performance since in most configurations /tmp will be disk I/O bound of course.
It may be worth adding this flag to the ChromicPDF API as an option, like with `no_sandbox`. But due to the performance concerns, whether this should be default or not is up for …

Add another known cause of crashing in Docker containers

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/protocols/navigate.ex
lib/chromic_pdf/supervisor.ex
test/integration/fixtures/test_dynamic.html
test/integration/pdf_generation_test.exs

This is useful for security, preventing exploitation of v8 bugs, SSRF and many other potential issues.
An alternative to this implementation(calling `Emulation.setScriptExecutionDisabled`) that can be used with the current version of chromic_pdf is to set the chromium flag `--blink-settings=scriptEnabled=false`, but because of the lack of stability or documentation of chromium cmdline flags I think this is a way better solution.

Add a disable_scripts navigation option

---

.circleci/config.yml
CHANGELOG.md
lib/chromic_pdf/pdf/browser/channel.ex
lib/chromic_pdf/pdf/protocol.ex
lib/chromic_pdf/pdf/protocol_macros.ex
lib/chromic_pdf/supervisor.ex
test/integration/pdf_generation_test.exs
test/unit/chromic_pdf/pdf/protocol_test.exs

This patch adds an `Inspect` implementation for `ChromicPDF.Protocol` that redacts any potentially sensitive data, leaving merely ChromicPDF internals and options. Next, the inspected protocol is included in the timeout error in `Channel.run_protocol/3`, as this is the error a lot of people run into in various situations: boot time, teardown, etc.
Relates to #160 
Relates to #171

Include inspected protocol in timeout error

---

test/integration/template_test.exs

This patch changes the page size assertion for our `size: :a4` test, as more recent Chrome/Skia versions generate slightly wider pages. 
To exactly pinpoint which version of Chrome brought the change, I'd need to bisect Chrome versions, but TBH I don't think we gain much from the information.
Both of these files were generated by the same command and analyzed using the same `pdfinfo` machine (on my host):
```elixir
[content: "<p>Hello</p>", size: :a4]
|> ChromicPDF.Template.source_and_options()
|> ChromicPDF.print_to_pdf(output: "file.pdf")
```
| Chrome |File | pdfinfo | Screenshot |
| - | -| -| -|
| v90 | [chrome90.pdf](https://github.com/bitcrowd/chromic_pdf/files/10148590/chrome90.pdf) | ![image](https://user-images.githubusercontent.com/96114/205493499-46482a1f-e08c-4f5e-b4a0-b89cfa7df …

Change page size assertion to match newer Chrome files

---

CHANGELOG.md
lib/chromic_pdf/pdf/chrome_impl.ex
test/integration/pdf_generation_test.exs
test/integration/pdfa_generation_test.exs
test/integration/support/test_api.ex

This patch extends our list of default command line argument passed
to Chrome based on Puppeteer's example.

Add more default command line arguments

---

test/integration/session_pool_test.exs

```
Since this test is configured to fail after a very short `init_timeout`,
NimblePool tries to restart the service a bunch of times, each time
sending a `createBrowserContext` message to Chrome.
This patch increases the timeout to 10ms, so at least we don't create a
hundred of them, but maybe 10 or so.
```
Open for better solutions on how to fix this

Reduce resource waste in test

---

lib/chromic_pdf/api.ex
lib/chromic_pdf/supervisor.ex

This patch slightly rearranges our parameter types to separate the export-specific options (output, telemetry) from the PDF printing-specific options.

Extract t:export_option from t:pdf_option

---

lib/chromic_pdf/pdf/protocol.ex

Hey there,
Since Elixir version requirement isn't specified, I'd love to make the latest version of the lib compatible with versions below 1.12, where Kernel.then was introduced.
Removing it was enough to make the lib compile using at least Elixir 1.11, haven't tried another versions.
Consider 1.10 almost deprecated https://hexdocs.pm/elixir/compatibility-and-deprecations.html
By the way, first PR in Open Source project, so let me know if something isn't right :)

compability with Elixir versions below  1.12 

---

.github/workflows/test.yaml
README.md
mix.exs

- Enable Elixir 1.11 test image
- Fix broken image repo (`-test-image`) in test workflow
- Set minimum required Elixir version to 1.11
- Document test matrix in README

Enable Elixir 1.11 test image

---

.github/workflows/lint.yaml
CHANGELOG.md
lib/chromic_pdf/pdf/browser/session_pool.ex
test/integration/session_pool_test.exs

This patch handles the `DOWN` reason in the `terminate_worker/3` callback, which we previously thought "would not happen", but a user reported it as "does happen indeed". Not 100% sure how or why it happens, but we don't expect anything to break if we handle it.
Fixes [#219](https://github.com/bitcrowd/chromic_pdf/issues/219)

[#219] Handle DOWN in terminate_worker/3

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/api/chrome_error.ex
lib/chromic_pdf/pdf/browser/session_pool.ex
lib/chromic_pdf/pdf/protocol.ex
lib/chromic_pdf/pdf/protocol_macros.ex
lib/chromic_pdf/pdf/protocols/spawn_session.ex
lib/chromic_pdf/supervisor.ex
test/integration/pdf_generation_test.exs

This patch adds the `:unhandled_runtime_exceptions` option that allows to configure sessions to raise a ChromeError when Chrome sends us a `Runtime.exceptionThrown` notification.
Relates to #237

Add :raise_on_unhandled_runtime_exceptions option

---

lib/chromic_pdf/pdf/browser/session_pool.ex
lib/chromic_pdf/pdf/protocol_macros.ex

with `Logger.warning/1` (available since Elixir 1.11.0)

Replace deprecated `Logger.warn/1` on Elixir 1.15.0

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/template.ex

This patch adds some documentation to guide people through the inevitable font rendering issues on Linux.
On Linux, Skia has issues rendering certain fonts, it especially completely messes up font kerning. Mitigations exist in the outlined options, yet we decided not to apply any by default, in order not to break any existing templates.
Also added a new `text_rendering` option to `ChromicPDF.Template` to allow easily setting that CSS rule on `*` elements.
- https://github.com/puppeteer/puppeteer/issues/2410
- https://www.browserless.io/blog/2020/09/30/puppeteer-print/
- https://css-tricks.com/almanac/properties/t/text-rendering/
- https://sonneiltech.com/2020/12/manage-your-websites-legibility-using-text-rendering-and-its-alternatives/
Below you can see test rendering of the same input …

Document fixes for font render issues.

---

.tool-versions
CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/api/chrome_error.ex
lib/chromic_pdf/pdf/protocol.ex
lib/chromic_pdf/pdf/protocol_macros.ex
lib/chromic_pdf/supervisor.ex
test/integration/pdf_generation_test.exs

This patch adds the `:console_api_calls` global option, which works the same as the `:unhandled_runtime_exception` option in that it can be set to `:ignore`, `:log`, or `:raise`. By default, console API calls are ignored.

Add :console_api_calls global option.

---

CHANGELOG.md
lib/chromic_pdf/pdf/chrome_runner.ex

[#270] Do no pass --no-zygote alongside --no-sandbox

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/browser.ex
lib/chromic_pdf/pdf/browser/channel.ex
lib/chromic_pdf/pdf/browser/session_pool.ex
lib/chromic_pdf/supervisor.ex
lib/chromic_pdf/utils.ex
test/integration/fixtures/test_exception.html
test/integration/pdf_generation_test.exs
test/integration/session_pool_test.exs
test/integration/support/test_api.ex

This adds support for multiple named session pools.
I figured that people in the past repeatedly wanted to have different values for our "global" options (e.g. `disable_scripts`) per print job, or rather likely per template. As this goes against my original idea of keeping "initialization work" strictly to the initialization (`SpawnSession`) and keep the amount of work per print job to a minimum, I'm inclined to point people to the existing possibility of launching multiple ChromicPDF instances with different configs (think: print queues). However, launching a separate ChromicPDF supervisor means launching additional OS processes of chromium, which seems wasteful. At this point I realized that we're lacking a middle layer in the session pool, i.e. differently configured sessions. This PR …

Add named session pools

---

lib/chromic_pdf/api.ex
lib/chromic_pdf/pdf/browser.ex
lib/chromic_pdf/pdf/browser/session_pool.ex
lib/chromic_pdf/pdf/browser/session_pool_config.ex
test/integration/support/get_targets.ex

- Refactors SessionPool to be only concerned with session counting
- Worker init & teardown is parameterized by passing in functions from browser now. These functions capture the config as needed.
- New Agent in Browser stores the pool configs by name for later lookup.

Refactor SessionPool, store pool config in agent

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/browser.ex
lib/chromic_pdf/pdf/browser/session_pool.ex
lib/chromic_pdf/pdf/browser/session_pool_config.ex
lib/chromic_pdf/supervisor.ex
test/integration/session_pool_test.exs

This patch adds a global `:checkout_timeout` option to configure the allowed wait-time of an operation in the session pool's queue.
This also deliberately drops the section on `:init_timeout` from the docs as I don't see why anyone would mess with that. Same goes for `:close_timeout` (configurable, but not advertised in the docs).
Fixes #276 
cc @axelclark

[#276] Make checkout timeout configurable

---

CHANGELOG.md
lib/chromic_pdf/template.ex
test/integration/support/test_api.ex
test/integration/template_test.exs

This patch adds `ChromicPDF.Template.options/1` to fetch the options for the `print_to_pdf/2` call without passing in the content.
Besides, styles generate by `Template.styles/1` are now squished.

Add Template.options/1

---

CHANGELOG.md
lib/chromic_pdf/pdf/chrome_runner.ex
lib/chromic_pdf/pdfa/ghostscript_runner.ex
lib/chromic_pdf/template.ex
lib/chromic_pdf/utils.ex
test/integration/screenshot_test.exs
test/unit/chromic_pdf/utils_test.exs

Fixes [[#290]](https://github.com/bitcrowd/chromic_pdf/issues/290)
Since Chrome 117 custom footers would not be displayed anymore when configured via `ChromicPDF.Template`. Reason for this was that our stylesheet was prepended to both the content markup as well as the header and footer templates. The `@page` rule contains the page margins which used to be ignored in the header and footer sections, but are not applied and lead to the footer being pushes out of its content box. Fixed by splitting `ChromicPDF.Template.styles/1` into `page_styles/1` and `header_footer_styles/1` and removing the `@page` directive from the header and footer styles.
Besides, this patch removes the `zoom` directive from the header and footer templates for Chrome >= v120, as they have removed the default 4/3 …

[#290] Fix missing footers

---

.github/workflows/test.yaml

See https://github.com/elixir-lang/elixir/issues/11484
Running `mix test --failed` will report passing tests if on the previous run no tests failed. No tests failed on the previous run if the test code didn't compile at all.
The problem can be reproduced by:
- Adding any invalid gibberish to any test file
- Running `mix test || mix test --failed`
- Running `$?` - it will report last exit code of 0, even though you can see compilation errors in the output from the first test run.

Only retry failed tests if the tests ran and failed

---

mix.exs

Chromic does not seem to rely on any functions removed in v4.0.0 : https://hexdocs.pm/phoenix_html/changelog.html

Allow phoenix_html 4.0

---

lib/chromic_pdf/supervisor.ex

Erlang's `mfa()` means module, function, **arity** and expects an integer as last tuple element.

Fix typespec for :forward option.

---

lib/chromic_pdf/pdf/browser/channel.ex

Took me a while to figure out what this comment was actually referring to, so I hope this helps out somebody else 🙂

fix: correct hint about how to set chrome args

---

lib/chromic_pdf/pdf/chrome_runner.ex

Add two filenames from the new Heroku Chrome buildpack https://blog.heroku.com/improved-browser-testing-on-heroku-with-chrome
The previous buildpacks I tried using Gigalixir didn't work:
https://github.com/heroku/heroku-buildpack-google-chrome
https://github.com/hermantolim/gigalixir-buildpack-google-chrome
However, the new "improved-browser-testing-on-heroku-with-chrome" installs as "chrome" and "chromedriver"
I tried just using `chrome_executable: chrome` to avoid a PR. Things I noticed with that:
1. It starts up fine, not complaining about finding the executable ✅
2. At the time to print it errors out saying it can't find the executable ❌
I believe `do_version` calls `executable()` without passing in the config options, so `chrome_executable` isn't being read.
```
** (RuntimeError) …
```

Add additional default executables from Heroku buildpack

---

lib/chromic_pdf/pdf/chrome_runner.ex
lib/chromic_pdf/template.ex

This makes the call to `ChromeRunner.version/0` optional in `Template` to allow people who use a non-standard `:chrome_executable` to also use the `Template` (by specifying the zoom explicitly). Unfortunately, taking the `:chrome_executable` into account is quite annoying in the template opts, so we may instead just want to document this better. Users can also set the application env key explicitly before running chromic.

Make ChromeRunner.version/0 optional in Template

---

lib/chromic_pdf/pdf/connection/inet.ex

Elixir 1.17 deprecated single-quotes to create charlists ([see changelog](https://github.com/elixir-lang/elixir/blob/ddf84aba7e60aae4541dee3b8225faff5b31cb32/CHANGELOG.md?plain=1#L189)). This project uses single-quotes in one place to create charlists, which this PR converts to `~c`.

Use `~c` in favor of single-quotes to create charlists

---

CHANGELOG.md
lib/chromic_pdf.ex
lib/chromic_pdf/pdf/chrome_runner.ex
lib/chromic_pdf/pdf/connection/local.ex
lib/chromic_pdf/supervisor.ex

When trying to use chromic_pdf in combination with pages that contain WebGL images, there are two default args in `ChromeRunner` that prevent it from working.
* `--headless` (rather than `--headless=new`) 
* `--disable-gpu` which, despite its name, will disable software based webgl rendering in addition to hardware accelerated webgl
Based on my experimentation, simply overriding these in `:chrome_args` is not enough. Once they are declared, they can't be overridden by further switches.
Instead of just taking these out, and maybe break other people's projects, I think adding the ability to remove the args via configuration is a more  useful feature.

Add ability to remove default args via config

---

CHANGELOG.md
lib/chromic_pdf/api.ex
lib/chromic_pdf/api/protocol_options.ex
lib/chromic_pdf/pdf/browser/channel.ex
lib/chromic_pdf/pdf/protocol.ex
lib/chromic_pdf/supervisor.ex
test/integration/custom_protocol_test.exs
test/integration/screenshot_test.exs
test/integration/support/get_targets.ex
test/integration/support/test_api.ex

This patch makes the API more versatile by allowing to run custom protocols.
- add `:protocol` option to `print_to_pdf/2` & `capture_screenshot/2`
- refactor API & options handling around `chrome_export/2`
- add new top-level, but hidden `run_protocol/2` API
For the time being, these features are not advertised in the documentation. The `ChromicPDF.Protocol` machinery can be quite tricky and the poor DSL in `ChromicPDF.ProtocolMacros` is subject to change. Nonetheless, this could be a way to avoid adding further options to change and extend the default protocols' behaviour.
Relates to #319

Support custom protocols

---

lib/chromic_pdf/pdf/protocol_macros.ex

Basically the main issue was when the description was missing. And it seems the description is missing when the passed error is `undefined`.
** Script **
```js
throw(undefined);
```
** Javascript console output: **
```
index.js:14 Uncaught undefined
```
** Chromic displayed message: **
```
Uncaught undefined
```
** Script **
```js
new Promise((_, reject) => reject())
```
** Javascript console output: **
```
index.js:15 Uncaught (in promise) undefined
```
** Chromic displayed message: **
```
Uncaught (in promise) undefined
```

#332 Fix exception message capture

---

CHANGELOG.md
lib/chromic_pdf/pdf/protocols/navigate.ex
lib/chromic_pdf/supervisor.ex
test/integration/pdf_generation_test.exs
test/integration/support/test_server.ex

For #336 
This PR adds a set_timezone option to the navigate protocol.

Timezone override
