- CHANGELOG.md
- lib/chromic_pdf.ex
- lib/chromic_pdf/pdf/protocols/print_to_pdf.ex
- lib/chromic_pdf/pdf/protocols/spawn_session.ex
- lib/chromic_pdf/pdf/session.ex
- lib/chromic_pdf/processor.ex
- lib/chromic_pdf/supervisor.ex
- test/integration/pdf_generation_test.exs
* Make offline mode toggleable.
* Navigate to blank page after printing.
* Update docs
* Fix temporary file yielding
> Tuesday updates

- CHANGELOG.md
- config/config.exs
- lib/chromic_pdf/pdf/protocol_macros.ex
- lib/chromic_pdf/pdf/protocols/print_to_pdf.ex
- lib/chromic_pdf/processor.ex
- lib/chromic_pdf/supervisor.ex
- mix.exs
- mix.lock
- test/integration/pdf_generation_test.exs
> Add support for cookies.

- CHANGELOG.md
- README.md
- lib/chromic_pdf/processor.ex
- lib/chromic_pdf/supervisor.ex
- lib/chromic_pdf/template.ex
- test/integration/template_test.exs
> Add template module.

- lib/chromic_pdf/api.ex
- lib/chromic_pdf/supervisor.ex
* Also, drop `:chromic_pdf` option, it's not needed anymore.
* Switch to `:one_for_one` supervisor strategy for top-level supervisor.
> Pass services as pids to API.

- CHANGELOG.md
- lib/chromic_pdf.ex
- lib/chromic_pdf/api.ex
- lib/chromic_pdf/supervisor.ex
- mix.exs
- mix.lock
- test/integration/telemetry_test.exs
> [65] Telemetry support

- CHANGELOG.md
- lib/chromic_pdf.ex
- lib/chromic_pdf/pdf/browser/session_pool.ex
- lib/chromic_pdf/supervisor.ex
- test/integration/pdf_generation_test.exs
> [66] Default to "online" mode

- CHANGELOG.md
- lib/chromic_pdf/pdf/chrome_impl.ex
> [76] Mix.Shell hangs when supervisor is started

- CHANGELOG.md
- lib/chromic_pdf.ex
- lib/chromic_pdf/pdf/chrome_impl.ex
- lib/chromic_pdf/pdf/connection.ex
- lib/chromic_pdf/supervisor.ex
- test/unit/chromic_pdf/pdf/connection_test.exs
> [91] Custom options to chromium

- lib/chromic_pdf.ex
Just randomly saw this one and thought I fix it directly.
> Fix spelling in the docs

- CHANGELOG.md
- mix.exs
> [#108] Function :telemetry.span/3 is undefined or private

- lib/chromic_pdf/pdf/protocol_macros.ex
> [105] Await_response not failing when payload does not contain key

- config/config.exs
- lib/chromic_pdf/pdf/connection/json_rpc.ex
> [107] Compile time debug option to log calls and Chrome messages

- lib/chromic_pdf/pdf/chrome_impl.ex
> [#151] Add more absolute paths to Chrome

- CHANGELOG.md
- lib/chromic_pdf/pdf/protocols/navigate.ex
- lib/chromic_pdf/pdf/protocols/spawn_session.ex
- lib/chromic_pdf/supervisor.ex
- test/integration/pdf_generation_test.exs
See discussion in https://github.com/bitcrowd/chromic_pdf/pull/167
> Make disable_scripts into a global option

- CHANGELOG.md
- lib/chromic_pdf.ex
- lib/chromic_pdf/pdf/protocols/spawn_session.ex
- test/integration/pdf_generation_test.exs
& refactor `:disable_scripts` a bit
> update security considerations section

- CHANGELOG.md
- README.md
- lib/chromic_pdf.ex
- lib/chromic_pdf/api.ex
- lib/chromic_pdf/api/export_options.ex
- lib/chromic_pdf/api/pdf_options.ex
- lib/chromic_pdf/pdfa/ghostscript.ex
- lib/chromic_pdf/pdfa/ghostscript_impl.ex
- lib/chromic_pdf/pdfa/ghostscript_pool.ex
- lib/chromic_pdf/pdfa/ghostscript_worker.ex
- lib/chromic_pdf/supervisor.ex
- test/integration/pdf_generation_test.exs
- test/integration/telemetry_test.exs
This patch refactors the merge feature a bit, basically "owning" the code. No functional changes here, only rewording, documentation shortening, etc.
- "merge" -> concatenate/join
> Refactor merge feature

- .circleci/config.yml
As it started happening to us now, too:
https://app.circleci.com/pipelines/github/bitcrowd/chromic_pdf/699/workflows/bf4b3561-58d9-40b6-b9e0-68e3b7c7c383/jobs/3891
> Call warm_up in our own CI pipeline

- README.md
- lib/chromic_pdf.ex
- lib/chromic_pdf/supervisor.ex
> [#207] Document state of accessibility with Chrome/Ghostscript

- CHANGELOG.md
- lib/chromic_pdf/pdfa/ghostscript_runner.ex
- lib/chromic_pdf/pdfa/ghostscript_worker.ex
- lib/chromic_pdf/supervisor.ex
- test/integration/zugferd_test.exs
Fixes [#215](https://github.com/bitcrowd/chromic_pdf/issues/215)
> [#215] Zugferd test is broken for SAFER ghostscript

- .github/docker/Dockerfile_alpine-3-16-2
- .github/docker/Dockerfile_alpine-3-17-0
[[#221]](https://github.com/bitcrowd/chromic_pdf/issues/221)
> [#221] Caching is broken for Alpine CI runs

- lib/chromic_pdf.ex
- lib/chromic_pdf/supervisor.ex
- test/integration/dynamic_name_test.exs
- test/integration/on_demand_test.exs
> Add support for the name option

- .github/docker/Dockerfile_alpine-3-16-2
- .github/docker/Dockerfile_alpine-3-17-3
- .github/docker/Dockerfile_debian-bullseye
- .github/docker/Dockerfile_debian-buster
- .github/docker/Dockerfile_elixir-1-11
- CHANGELOG.md
- lib/chromic_pdf/pdf/protocols/capture_screenshot.ex
- lib/chromic_pdf/supervisor.ex
- test/integration/fixtures/large.html
- test/integration/screenshot_test.exs
- test/test_helper.exs
See https://github.com/puppeteer/puppeteer/blob/9c00c2c57e8b698c266a9b463c4601ec730d033f/packages/puppeteer-core/src/common/Page.ts#L1362-L1389 for reference
> Add :full_page option to capture_screenshot/2

- CHANGELOG.md
- lib/chromic_pdf/pdfa/ghostscript_runner.ex
> Drop NEWPDF=false switch for recent Ghostscript

- CHANGELOG.md
- lib/chromic_pdf/pdf/chrome_runner.ex
> Extract version from version string after app config
